const nodemailer = require('nodemailer');

// Ensure you have these env vars set, or replace with valid SMTP for testing
const transporter = nodemailer.createTransport({
    service: 'gmail', // You can use other services
    auth: {
        user: process.env.EMAIL_USER || 'smarttrack.alerts@gmail.com', // Placeholder
        pass: process.env.EMAIL_PASS || 'your-app-password'
    }
});

const sendAlertEmail = async (toEmail, fullName, alertType, details, screenshotBase64) => {
    try {
        const mailOptions = {
            from: process.env.EMAIL_USER || 'smarttrack.alerts@gmail.com',
            to: toEmail,
            subject: `⚠️ SECURITY ALERT: ${alertType} - ${fullName}`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; padding: 20px; border: 1px solid #e2e8f0; border-radius: 10px;">
                    <h2 style="color: #e11d48;">SmartTrack Security Alert</h2>
                    <p><strong>Employee:</strong> ${fullName}</p>
                    <p><strong>Alert Type:</strong> ${alertType}</p>
                    <p><strong>Details:</strong> ${details}</p>
                    <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
                    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
                    <h3>Incident Evidence</h3>
                    ${screenshotBase64 ? `<img src="${screenshotBase64}" style="width: 100%; border-radius: 5px; border: 1px solid #ccc;"/>` : '<p>No screenshot evidence captured.</p>'}
                    <p style="font-size: 12px; color: #64748b; margin-top: 20px;">This is an automated administrative notification generated by SmartTrack.ai</p>
                </div>
            `
        };

        const info = await transporter.sendMail(mailOptions);
        console.log(`Email alert sent to ${toEmail}: ${info.messageId}`);
    } catch (error) {
        console.error("Error sending email alert:", error);
    }
};

module.exports = { sendAlertEmail };
